package main

import "net/http"

// generatedDispatch maps each lowercase HTTP route name to its handler
// method, generated from every tools/generator/metadata/*.json file - see
// tools/generator/templates/dispatch.tmpl. Do not hand-edit - regenerate
// via `cd tools/generator && go run . -all-handlers` instead. Replaces
// what used to be a hand-maintained switch statement in
// StatsHandler.ServeHTTP.
var generatedDispatch = map[string]func(*StatsHandler, http.ResponseWriter, *http.Request){
	"playerdashboardbygeneralsplits":   (*StatsHandler).handlePlayerDashboardByGeneralSplits,
	"teamdashboardbygeneralsplits":     (*StatsHandler).handleTeamDashboardByGeneralSplits,
	"playbyplayv2":                     (*StatsHandler).handlePlayByPlayV2,
	"boxscoretraditionalv2":            (*StatsHandler).handleBoxScoreTraditionalV2,
	"leaguegamefinder":                 (*StatsHandler).handleLeagueGameFinder,
	"teamgamelogs":                     (*StatsHandler).handleTeamGameLogs,
	"boxscoresummaryv2":                (*StatsHandler).handleBoxScoreSummaryV2,
	"shotchartdetail":                  (*StatsHandler).handleShotChartDetail,
	"teamyearbyyearstats":              (*StatsHandler).handleTeamYearByYearStats,
	"commonplayerinfo":                 (*StatsHandler).handleCommonPlayerInfo,
	"playergamelog":                    (*StatsHandler).handlePlayerGameLog,
	"teamgamelog":                      (*StatsHandler).handleTeamGameLog,
	"playercareerstats":                (*StatsHandler).handlePlayerCareerStats,
	"leagueleaders":                    (*StatsHandler).handleLeagueLeaders,
	"internationalbroadcasterschedule": (*StatsHandler).handleInternationalBroadcasterSchedule,
	"commonallplayers":                 (*StatsHandler).handleCommonAllPlayers,
	"commonteamroster":                 (*StatsHandler).handleCommonTeamRoster,
	"leaguedashplayerstats":            (*StatsHandler).handleLeagueDashPlayerStats,
	"leaguedashteamstats":              (*StatsHandler).handleLeagueDashTeamStats,
	"scoreboardv2":                     (*StatsHandler).handleScoreboardV2,
	"playerprofilev2":                  (*StatsHandler).handlePlayerProfileV2,
	"leaguestandings":                  (*StatsHandler).handleLeagueStandings,
	"boxscoreadvancedv2":               (*StatsHandler).handleBoxScoreAdvancedV2,
	"teaminfocommon":                   (*StatsHandler).handleTeamInfoCommon,
	"leaguehustlestatsteamleaders":     (*StatsHandler).handleLeagueHustleStatsTeamLeaders,
	"teamplayeronoffdetails":           (*StatsHandler).handleTeamPlayerOnOffDetails,
	"teamplayeronoffsummary":           (*StatsHandler).handleTeamPlayerOnOffSummary,
	"playerestimatedadvancedstats":     (*StatsHandler).handlePlayerEstimatedAdvancedStats,
	"leaguedashptstats":                (*StatsHandler).handleLeagueDashPtStats,
	"playertrackingspeeddistance":      (*StatsHandler).handlePlayerTrackingSpeedDistance,
	"playertrackingrebounding":         (*StatsHandler).handlePlayerTrackingRebounding,
	"playertrackingpasses":             (*StatsHandler).handlePlayerTrackingPasses,
	"playertrackingelbowtouch":         (*StatsHandler).handlePlayerTrackingElbowTouch,
	"playertrackingposttouch":          (*StatsHandler).handlePlayerTrackingPostTouch,
	"playertrackingpainttouch":         (*StatsHandler).handlePlayerTrackingPaintTouch,
	"playertrackingdrives":             (*StatsHandler).handlePlayerTrackingDrives,
	"playertrackingcatchshoot":         (*StatsHandler).handlePlayerTrackingCatchShoot,
	"playertrackingpullupshot":         (*StatsHandler).handlePlayerTrackingPullUpShot,
	"playertrackingdefense":            (*StatsHandler).handlePlayerTrackingDefense,
	"leaguedashlineups":                (*StatsHandler).handleLeagueDashLineups,
	"teamyearoveryearsplits":           (*StatsHandler).handleTeamYearOverYearSplits,
	"playerdashboardbygamesplits":      (*StatsHandler).handlePlayerDashboardByGameSplits,
	"teamdashboardbygamesplits":        (*StatsHandler).handleTeamDashboardByGameSplits,
	"leagueplayerondetails":            (*StatsHandler).handleLeaguePlayerOnDetails,
	"leaguestandingsv3":                (*StatsHandler).handleLeagueStandingsV3,
	"commonteamrosterv2":               (*StatsHandler).handleCommonTeamRosterV2,
	"teamvsteam":                       (*StatsHandler).handleTeamVsTeam,
	"playergamelogs":                   (*StatsHandler).handlePlayerGameLogs,
	"boxscoredefensivev2":              (*StatsHandler).handleBoxScoreDefensiveV2,
	"boxscorehustlev2":                 (*StatsHandler).handleBoxScoreHustleV2,
	"playbyplayv3":                     (*StatsHandler).handlePlayByPlayV3,
	"leaguedashteamclutchv2":           (*StatsHandler).handleLeagueDashTeamClutchV2,
	"leaguedashplayerclutchv2":         (*StatsHandler).handleLeagueDashPlayerClutchV2,
	"shotchartlineupdetail":            (*StatsHandler).handleShotChartLineupDetail,
	"commonallplayersv2":               (*StatsHandler).handleCommonAllPlayersV2,
	"leagueleadersv2":                  (*StatsHandler).handleLeagueLeadersV2,
	"commonplayoffseriesv2":            (*StatsHandler).handleCommonPlayoffSeriesV2,
	"leaguedashplayershotlocationv2":   (*StatsHandler).handleLeagueDashPlayerShotLocationV2,
	"leaguegamelog":                    (*StatsHandler).handleLeagueGameLog,
	"playerawards":                     (*StatsHandler).handlePlayerAwards,
	"playoffpicture":                   (*StatsHandler).handlePlayoffPicture,
	"teamdashboardbyyearoveryear":      (*StatsHandler).handleTeamDashboardByYearOverYear,
	"playerdashboardbyyearoveryear":    (*StatsHandler).handlePlayerDashboardByYearOverYear,
	"playervsplayer":                   (*StatsHandler).handlePlayerVsPlayer,
	"teamvsplayer":                     (*StatsHandler).handleTeamVsPlayer,
	"draftcombinestats":                (*StatsHandler).handleDraftCombineStats,
	"playerdashptshots":                (*StatsHandler).handlePlayerDashPtShots,
	"leaguedashplayerptshot":           (*StatsHandler).handleLeagueDashPlayerPtShot,
	"playerdashboardbyshootingsplits":  (*StatsHandler).handlePlayerDashboardByShootingSplits,
	"teamdashboardbyshootingsplits":    (*StatsHandler).handleTeamDashboardByShootingSplits,
	"boxscorematchupsv3":               (*StatsHandler).handleBoxScoreMatchupsV3,
	"leaguedashptdefend":               (*StatsHandler).handleLeagueDashPtDefend,
	"leaguehustlestatsplayer":          (*StatsHandler).handleLeagueHustleStatsPlayer,
	"leaguehustlestatsteam":            (*StatsHandler).handleLeagueHustleStatsTeam,
	"playerestimatedmetrics":           (*StatsHandler).handlePlayerEstimatedMetrics,
	"leaguedashplayerclutch":           (*StatsHandler).handleLeagueDashPlayerClutch,
	"leaguedashteamclutch":             (*StatsHandler).handleLeagueDashTeamClutch,
	"synergyplaytypes":                 (*StatsHandler).handleSynergyPlayTypes,
	"franchisehistory":                 (*StatsHandler).handleFranchiseHistory,
	"franchiseleaders":                 (*StatsHandler).handleFranchiseLeaders,
	"teamhistoricalleaders":            (*StatsHandler).handleTeamHistoricalLeaders,
	"alltimeleadersgrids":              (*StatsHandler).handleAllTimeLeadersGrids,
	"playercompare":                    (*StatsHandler).handlePlayerCompare,
	"teamdashptshots":                  (*StatsHandler).handleTeamDashPtShots,
	"teamdashboardbyclutch":            (*StatsHandler).handleTeamDashboardByClutch,
	"playerdashboardbyclutch":          (*StatsHandler).handlePlayerDashboardByClutch,
	"playerdashboardbyopponent":        (*StatsHandler).handlePlayerDashboardByOpponent,
	"teamdashboardbyopponent":          (*StatsHandler).handleTeamDashboardByOpponent,
	"leaguedashteamshotlocations":      (*StatsHandler).handleLeagueDashTeamShotLocations,
	"leaguedashplayershotlocations":    (*StatsHandler).handleLeagueDashPlayerShotLocations,
	"teamplayerdashboard":              (*StatsHandler).handleTeamPlayerDashboard,
	"playergamestreakfinder":           (*StatsHandler).handlePlayerGameStreakFinder,
	"teamgamestreakfinder":             (*StatsHandler).handleTeamGameStreakFinder,
	"leaguedashteamptshot":             (*StatsHandler).handleLeagueDashTeamPtShot,
	"commonteamyears":                  (*StatsHandler).handleCommonTeamYears,
	"commonplayoffseries":              (*StatsHandler).handleCommonPlayoffSeries,
	"teamdetails":                      (*StatsHandler).handleTeamDetails,
	"teaminfocommonv2":                 (*StatsHandler).handleTeamInfoCommonV2,
	"playerindex":                      (*StatsHandler).handlePlayerIndex,
	"boxscoreplayertrackv2":            (*StatsHandler).handleBoxScorePlayerTrackV2,
	"boxscorefourfactorsv2":            (*StatsHandler).handleBoxScoreFourFactorsV2,
	"boxscorescoringv2":                (*StatsHandler).handleBoxScoreScoringV2,
	"boxscoreusagev2":                  (*StatsHandler).handleBoxScoreUsageV2,
	"videoevents":                      (*StatsHandler).handleVideoEvents,
	"winprobabilitypbp":                (*StatsHandler).handleWinProbabilityPBP,
	"gamerotation":                     (*StatsHandler).handleGameRotation,
	"boxscoremiscv2":                   (*StatsHandler).handleBoxScoreMiscV2,
	"leaguedashoppptshot":              (*StatsHandler).handleLeagueDashOppPtShot,
	"teamdashboardbylastngames":        (*StatsHandler).handleTeamDashboardByLastNGames,
	"playerdashboardbylastngames":      (*StatsHandler).handlePlayerDashboardByLastNGames,
	"leaguedashptteamdefend":           (*StatsHandler).handleLeagueDashPtTeamDefend,
	"teamestimatedmetrics":             (*StatsHandler).handleTeamEstimatedMetrics,
	"commonplayerinfov2":               (*StatsHandler).handleCommonPlayerInfoV2,
	"playerdashboardbyteamperformance": (*StatsHandler).handlePlayerDashboardByTeamPerformance,
	"teamdashboardbyteamperformance":   (*StatsHandler).handleTeamDashboardByTeamPerformance,
	"leaguedashplayerbiostats":         (*StatsHandler).handleLeagueDashPlayerBioStats,
	"leaguedashteambiostats":           (*StatsHandler).handleLeagueDashTeamBioStats,
	"scoreboardv3":                     (*StatsHandler).handleScoreboardV3,
	"infographicfanduelplayer":         (*StatsHandler).handleInfographicFanDuelPlayer,
	"playerfantasyprofile":             (*StatsHandler).handlePlayerFantasyProfile,
	"assisttracker":                    (*StatsHandler).handleAssistTracker,
	"assistleaders":                    (*StatsHandler).handleAssistLeaders,
	"cumestatsplayer":                  (*StatsHandler).handleCumeStatsPlayer,
	"cumestatsteam":                    (*StatsHandler).handleCumeStatsTeam,
	"defensehub":                       (*StatsHandler).handleDefenseHub,
	"homepageleaders":                  (*StatsHandler).handleHomepageLeaders,
	"homepagev2":                       (*StatsHandler).handleHomepageV2,
	"matchuprollup":                    (*StatsHandler).handleMatchupRollup,
	"playertrackingshootingefficiency": (*StatsHandler).handlePlayerTrackingShootingEfficiency,
	"shootingefficiency":               (*StatsHandler).handleShootingEfficiency,
	"opponentshooting":                 (*StatsHandler).handleOpponentShooting,
	"playeryearbyyearstats":            (*StatsHandler).handlePlayerYearByYearStats,
	"teamlineups":                      (*StatsHandler).handleTeamLineups,
	"leagueseasonmatchups":             (*StatsHandler).handleLeagueSeasonMatchups,
	"teamandplayersvsplayers":          (*StatsHandler).handleTeamAndPlayersVsPlayers,
	"playernextngames":                 (*StatsHandler).handlePlayerNextNGames,
	"teamnextngames":                   (*StatsHandler).handleTeamNextNGames,
	"playercareerbycollege":            (*StatsHandler).handlePlayerCareerByCollege,
	"playercareerbycollegerollup":      (*StatsHandler).handlePlayerCareerByCollegeRollup,
	"drafthistory":                     (*StatsHandler).handleDraftHistory,
	"draftboard":                       (*StatsHandler).handleDraftBoard,

	// Legacy route alias, not derived from metadata: "playertrackingshotdashboard"
	// was the original route name for what metadata now calls
	// PlayerTrackingShootingEfficiency. Kept for backward compatibility with
	// any caller still using the old path - see cmd/nba-api-server/main.go's
	// EndpointsCount comment (http_exposed is 1 higher than sdk_total because
	// of this single alias).
	"playertrackingshotdashboard": (*StatsHandler).handlePlayerTrackingShootingEfficiency,
}
